name: data_guardian
description: "A new Flutter project."
# Prevents the package from being accidentally published to pub.dev
publish_to: 'none' 

# Version and build configuration
version: 1.0.0+1
# Version number is formatted as x.y.z where x is the major version,
# y is the minor, and z is the patch version.
# The build number follows the + sign.

environment:
  sdk: '>=3.4.0 <4.0.0'  # Specifies the SDK version constraints

# Dependencies section specifies third-party packages or libraries that your project depends on
dependencies:
  flutter:
    sdk: flutter  # Dependency on the Flutter SDK

  cupertino_icons: ^1.0.6  # Provides iOS-style icons

# Development dependencies section for packages and tools that assist in development but aren't included in the app's production build
dev_dependencies:
  flutter_test:
    sdk: flutter  # Includes Flutter's testing framework

  flutter_lints: ^3.0.0  # Provides a recommended set of lints to encourage good coding practices

# Flutter-specific configuration options
flutter:
  uses-material-design: true  # Includes the Material Design icons with the application

  # Assets section for including images, config files, or other data files in the project
  assets:
    - images/spying.jpg  # Includes an image asset for use within the app
    - images\remote.jpg
  # Fonts section for adding custom fonts
  # fonts:
  #   - family: Schyler  # Font family name
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf  # Regular style font
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic  # Italic style font
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700  # Bold style font
  # For custom fonts, uncomment the above section and replace with your actual font files
